version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: '[Actions]'

  # Enable version updates for Docker
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    commit-message:
      prefix: '[Docker]'
